# Generated by Django 5.0.6 on 2024-05-23 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
