# Generated by Django 5.0.6 on 2024-05-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_refugio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refugio',
            name='is_active',
        ),
    ]
